### ISSUE TITLE
strimzi SSL

### ISSUE THREAD

**Issue by jesusmah** [birdayz/kaf#112]
Default Strimzi operator installs with TLS enabled with a crt certificate but no user or password at all. I could not make Kaf to work with just the TLS certificate. I could not find anything in the documentation or examples folder explaining this connectivity mode. 

So far, I am configuring my cluster like:

```
- name: strimzi
  brokers:
  - my-cluster-kafka-bootstrap-kafka-strimzi.apps.openshift.mydomain.com:443
  SASL: null
  TLS:
    cafile: /Users/user/ca.crt
    clientfile: ""
    clientkeyfile: ""
    insecure: true
  security-protocol: SASL_SSL
  schema-registry-url: ""
```

The output for that configuration is:

```
$ kaf topics               
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1641e92]

goroutine 1 [running]:
main.getConfig(0xc000161260)
	/home/j0e/projects/kaf/cmd/kaf/kaf.go:88 +0x172
main.getClusterAdmin(0xc0002540e8, 0xc000161260)
	/home/j0e/projects/kaf/cmd/kaf/kaf.go:177 +0x26
main.glob..func16(0x1e183e0, 0x1e3c468, 0x0, 0x0)
	/home/j0e/projects/kaf/cmd/kaf/topic.go:53 +0x37
github.com/spf13/cobra.(*Command).execute(0x1e183e0, 0x1e3c468, 0x0, 0x0, 0x1e183e0, 0x1e3c468)
	/home/j0e/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1e165e0, 0x17d2f3e, 0xc000207f50, 0x100543f)
	/home/j0e/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/j0e/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/j0e/projects/kaf/cmd/kaf/kaf.go:105 +0x31
```

If I change the `secutiry-protocol` to `SSL` I get the following:

```
$ kaf topics      
Unable to read Clientfile :open : no such file or directory
```

Thanks

**Comment by birdayz** [comment]
Can you try this:
```
  SASL:
    mechanism: SCRAM-SHA-512
    username: ""
    password: ""
  security-protocol: SASL_PLAINTEXT
```

**Comment by jesusmah** [comment]
hi @birdayz, with the config above I get

```
Unable to read Clientfile :open : no such file or directory
```

**Comment by birdayz** [comment]
i'll check it this evening with a fresh strimzi cluster. :)

**Comment by birdayz** [comment]
i tried yesterday; default strimzi manifest does not use TLS. can you help me a bit with the config, how is it set up? TLS listener with auth SCRAM?

**Comment by jesusmah** [comment]
@birdayz sorry I thought I had mentioned it... For Strimzi to be accessible outside my OpenShift cluster, I changed the default kafka manifest provided by Strimzi to add a external route in the listeners section. So my manifest looks like:

```yaml
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
      external:
        type: route
    config:
```

And that, as I said, creates a secured route in openshift you then use to access the kafka bootstrap server along with the ca certificate that can be obtained from the `<cluster_name>-cluster-ca-cert`

The way I am testing my srtrimzi kafka cluster is working fine is by using their `strimzi/kafka` docker image that comes with scripts for testing:

```bash
docker run -ti -v $(pwd):/home strimzi/kafka:latest-kafka-2.4.0  bash
# inside the container uses the consumer tool
bash-4.2$ cd /opt/kafka/bin
bash-4.2$ ./kafka-console-consumer.sh --bootstrap-server  <openshift_route>:443 --consumer-property security.protocol=SSL --consumer-property ssl.truststore.password=password --consumer-property ssl.truststore.location=/home/truststore.jks --topic test --from-beginning
``` 
(Yeah, you need to transform your ca cert into a jks truststore)

FYI, I've followed the instructions we've written to install the strimzi operator in an openshift cluster at https://ibm-cloud-architecture.github.io/refarch-eda/deployments/strimzi/deploy/
but now I wanted to get Kaf to work with such cluster

**Comment by birdayz** [comment]
Question: What is actually used to authenticate the client? No client cert, but also no user/password..?

**Comment by jesusmah** [comment]
Right, I am not very good at security myself so I dont know what is best or what the standards are. All I know is that for this 'external route' connectivity option that Strimzi offers in OpenShift all that is provided and needed in order for applications to connect to the cluster is the bootstrap server (<openshift_route>:443) and the ca cert (or jks you build from it)

**Comment by jesusmah** [comment]
It also works with some python scripts I run locally and in the producer and consumer configuration you can see what I am providing to the python clients:

```shell
root@c457043c8886:/tmp/lab/src# python ProducePlainMessage.py my-topic

 @@@ Executing script: producePlainMessage.py
The arguments for this script are:  ['ProducePlainMessage.py', 'my-topic']

Creating event...
DONE
--- Event to be published: ---
{'eventKey': '2', 'message': 'This is a test message'}

----------------------------------------
--- This is the configuration for the producer: ---
{'bootstrap.servers': 'my-cluster-kafka-bootstrap-kafka-strimzi.apps.xxxx:443', 'group.id': 'ProducePlainMessagePython', 'security.protocol': 'SSL', 'ssl.ca.location': '/tmp/lab/ca.crt'}
---------------------------------------------------

Message delivered to my-topic [0]

root@c457043c8886:/tmp/lab/src# python ConsumePlainMessage.py my-topic

 @@@ Executing script: ConsumePlainMessage.py
The arguments for this script are:  ['ConsumePlainMessage.py', 'my-topic']

--- This is the configuration for the consumer: ---
{'bootstrap.servers': 'my-cluster-kafka-bootstrap-kafka-strimzi.apps.xxxx:443', 'group.id': 'ConsumePlainMessagePython', 'auto.offset.reset': 'earliest', 'enable.auto.commit': True, 'security.protocol': 'SSL', 'ssl.ca.location': '/tmp/lab/ca.crt'}
---------------------------------------------------

[Message] - Next Message consumed from my-topic partition: [0] at offset 7 with key b'2':
	message: {"eventKey": "2", "message": "This is a test message"}
```

**Comment by birdayz** [comment]
i have trouble reproducing.

so there's basically 3 problems:
1) docs are bad. i'll work on this over the next few days.
2) code configuring SASL/SSL stuff is not very good and we have more options than needed. (security_mechanism and another sasl mechanism field)
3) i can't reproduce; i don't get the panic with these options:

```
- name: blatest
  brokers:
  - localhost:9092
  SASL: null
  TLS:
    cafile: <...path to some cert>
    clientfile: ""
    clientkeyfile: ""
    insecure: true
  security-protocol: SASL_SSL
```

the broker does not really exist, but the error is happening before a connection is initiated.

i think you use a different version of kaf than mine/master, the line of your panic does not match the code. can you retry using the latest version? i did a fresh release, https://github.com/birdayz/kaf/releases/tag/v0.1.36

**Comment by jesusmah** [comment]
@birdayz sorry I was not using the latest version apparently. It does not work with the latest version and the following configuration:

```yaml
- name: strimzi
  version: ""
  brokers:
  - my-cluster-kafka-bootstrap-kafka-strimzi.apps.xxxx:443
  SASL: null
  TLS:
    cafile: /Users/user/ca.crt
    clientfile: ""
    clientkeyfile: ""
    insecure: true
  security-protocol: SSL
  schema-registry-url: ""
```
Thanks a lot for your help
