### ISSUE TITLE
Using bootstrap servers?

### ISSUE THREAD

**Issue by Nielius** [birdayz/kaf#120]
Is it possible to specify a bootstrap server rather than a broker in the configuration file?

My configuration looks something like this:

```
clusters:
- name: test
  version: ""
  brokers:
  - someurl:9092
  TLS:
    cafile: ca.pem
    clientfile: public.pem
    clientkeyfile: private.pem
    insecure: false
  security-protocol: ""
  schema-registry-url: ""
```

and if `someurl` points to a broker, it works. However, if it points to a bootstrap server and I do for example `kaf topics`, I get

```
Unable to get cluster admin: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```
