### ISSUE TITLE
kaf config api version group query failed

### ISSUE THREAD

**Issue by xiaoxiong581** [birdayz/kaf#293]
kaf version:
0.2.3

kafka version:
2.12_2.3.0

kaf config:
```yaml
current-cluster: test
clusteroverride:
clusters:
- name: test
  version: 2.3.0
```
when config kaf config version 2.3.0, execute "kaf --config config groups " occur error: "Unable to describe consumer groups: EOF"
