### ISSUE TITLE
Unable to kaf consume and decode messages encoded with schema references (Avro type: unknown type name)

### ISSUE THREAD

**Issue by jeffkni** [birdayz/kaf#308]
### Kaf config (~/.kaf/config)
```
current-cluster: local
clusteroverride: ""
clusters:
- name: local
  version: ""
  brokers:
  - localhost:9092
  SASL:
    mechanism: PLAIN
    username: admin
    password: admin-secret
    clientID: ""
    clientSecret: ""
    tokenURL: ""
    token: ""
  TLS: null
  security-protocol: SASL_PLAINTEXT
  schema-registry-url: http://localhost:8082
```

### Steps to Reproduce

1. [Schema Registry](https://hub.docker.com/r/confluentinc/cp-schema-registry) + [Kafka](https://hub.docker.com/r/confluentinc/confluent-local#!) running in docker
    - Expose schema reg in docker to local :8082
1. Publish schemas **that have schema references** to the schema registry
1. emit an avro-encoded message to the topic
   - The encoded message was produced from code that used codegen with schema references
1. `kaf consume --verbose -f my.topic` to read it

**Expected result**: kaf decodes the message the way it does when there are no schema references. 
**Actual result**: kaf can't decode the message. With `--verbose` you can see kaf complain it doesn't understand the reference type:
```
could not decode Avro data: Record "MySpecialType" field 2 ought to be valid Avro named type: 
Union item 2 ought to be valid Avro type: unknown type name:
 "com.mycompany.common.MySharedType"
```

### Workaround

Confluent Schema Registry ships with an exe [kafka-avro-console-consumer
](https://developer.confluent.io/tutorials/kafka-console-consumer-producer-avro/kafka.html) that can be used to tail Kafka topics with "live" message decoding of messages that contain schema references. If you're using docker:

```bash
docker exec -it schema-registry /bin/bash -c "kafka-avro-console-consumer --topic my.super.topic \
  --bootstrap-server kafka:29092 --consumer-property security.protocol=SASL_PLAINTEXT \
  --consumer-property sasl.jaas.config='org.apache.kafka.common.security.plain.PlainLoginModule required username=my-kafka-username password=my-kafka-password;' \
  --consumer-property sasl.mechanism=PLAIN --property schema.registry.url=http://localhost:8082"
```

Note the `kafka:29092` port comes from the KAFKA_LISTENERS config in docker-compose.yaml, for example:

```yaml
  kafka:
    image: confluentinc/confluent-local
    hostname: kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENERS: 'INTERNAL://kafka:29092,CONTROLLER://kafka:29093,EXTERNAL://0.0.0.0:9092'
   [...]
```
